<a href="https://colab.research.google.com/github/shivaniii24/Machine-Learning-Project/blob/main/AdultIncome.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df= pd.read_csv("/content/AdultIncome.csv")

In [ ]:
df

age        wc      education  ...   gender hours per week IncomeClass
0       38   Private        HS-grad  ...     Male             40       <=50K
1       28   Private      Bachelors  ...   Female             40       <=50K
2       37   Private        Masters  ...   Female             40       <=50K
3       31   Private        Masters  ...   Female             50        >50K
4       42   Private      Bachelors  ...     Male             40        >50K
...    ...       ...            ...  ...      ...            ...         ...
19782   53   Private        Masters  ...     Male             40        >50K
19783   22   Private   Some-college  ...     Male             40       <=50K
19784   40   Private        HS-grad  ...     Male             40        >50K
19785   58   Private        HS-grad  ...   Female             40       <=50K
19786   22   Private        HS-grad  ...     Male             20       <=50K

[19787 rows x 8 columns]

In [ ]:
df.isnull().sum()

age               0
wc                0
education         0
marital status    0
race              0
gender            0
hours per week    0
IncomeClass       0
dtype: int64

In [ ]:
df = pd.get_dummies(df,drop_first=True)

In [ ]:
df

age  hours per week  ...  gender_ Male  IncomeClass_ >50K
0       38              40  ...             1                  0
1       28              40  ...             0                  0
2       37              40  ...             0                  0
3       31              50  ...             0                  1
4       42              40  ...             1                  1
...    ...             ...  ...           ...                ...
19782   53              40  ...             1                  1
19783   22              40  ...             1                  0
19784   40              40  ...             1                  1
19785   58              40  ...             0                  0
19786   22              20  ...             1                  0

[19787 rows x 20 columns]

In [ ]:
x = df.iloc[:,:-1].values
y = df.iloc[:, -1].values

In [ ]:
from sklearn.model_selection import train_test_split 

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25, random_state = 0)

In [ ]:
x_test

array([[33, 45,  0, ...,  0,  1,  1],
       [53, 50,  1, ...,  0,  1,  0],
       [31, 45,  0, ...,  0,  1,  1],
       ...,
       [35, 30,  0, ...,  0,  1,  0],
       [32, 60,  0, ...,  0,  1,  1],
       [27, 40,  0, ...,  0,  1,  1]])

In [ ]:
y_test

array([0, 1, 1, ..., 0, 0, 0], dtype=uint8)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dtc = DecisionTreeClassifier(random_state=0)

In [ ]:
 dtc.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
y_pred = dtc.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
confusion_matrix(y_test, y_pred)

array([[3154,  461],
       [ 633,  699]])

In [ ]:
accuracy_score(y_test, y_pred)

0.7788558722458055

Ensemble Techniques

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier(random_state=0)

In [ ]:
rfc.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
y_predrfc = rfc.predict(x_test)

In [ ]:
confusion_matrix(y_test, y_predrfc)

array([[3181,  434],
       [ 571,  761]])

In [ ]:
accuracy_score(y_test, y_predrfc)

0.7968465736810187